# CIDRA Framework - Windows Installer
# Usage: .\install.ps1 [-ProjectPath <path>] [-Force] [-Uninstall]
#
# Examples:
#   .\install.ps1                           # Install to current directory
#   .\install.ps1 -ProjectPath "C:\myproject"  # Install to specific project
#   .\install.ps1 -Force                    # Overwrite existing installation
#   .\install.ps1 -Uninstall                # Remove installation

param(
    [string]$ProjectPath = ".",
    [switch]$Force,
    [switch]$Uninstall,
    [switch]$Help
)

# Colors
$Green = "Green"
$Yellow = "Yellow"
$Red = "Red"
$Cyan = "Cyan"

# Script directory (where CIDRA framework is located)
$ScriptDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)

function Show-Banner {
    Write-Host ""
    Write-Host "  ██████╗██╗██████╗ ██████╗  █████╗ " -ForegroundColor $Cyan
    Write-Host " ██╔════╝██║██╔══██╗██╔══██╗██╔══██╗" -ForegroundColor $Cyan
    Write-Host " ██║     ██║██║  ██║██████╔╝███████║" -ForegroundColor $Cyan
    Write-Host " ██║     ██║██║  ██║██╔══██╗██╔══██║" -ForegroundColor $Cyan
    Write-Host " ╚██████╗██║██████╔╝██║  ██║██║  ██║" -ForegroundColor $Cyan
    Write-Host "  ╚═════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝" -ForegroundColor $Cyan
    Write-Host ""
    Write-Host " CIDRA Framework Installer" -ForegroundColor $Yellow
    Write-Host " Chunker + Interpreter + Documenter + Recommender + Applicator" -ForegroundColor $Yellow
    Write-Host " Version 1.0.0" -ForegroundColor $Yellow
    Write-Host ""
}

function Show-Help {
    Show-Banner
    Write-Host "Usage: .\install.ps1 [options]" -ForegroundColor $Green
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -ProjectPath <path>  Target project directory (default: current)"
    Write-Host "  -Force               Overwrite existing installation"
    Write-Host "  -Uninstall           Remove CIDRA from project"
    Write-Host "  -Help                Show this help message"
    Write-Host ""
    Write-Host "Examples:"
    Write-Host "  .\install.ps1"
    Write-Host "  .\install.ps1 -ProjectPath 'C:\myproject'"
    Write-Host "  .\install.ps1 -Force"
    Write-Host "  .\install.ps1 -Uninstall"
    Write-Host ""
}

function Test-Prerequisites {
    Write-Host "Checking prerequisites..." -ForegroundColor $Yellow

    # Check if project path exists
    if (-not (Test-Path $ProjectPath)) {
        Write-Host "ERROR: Project path does not exist: $ProjectPath" -ForegroundColor $Red
        return $false
    }

    # Check if CIDRA framework files exist
    $agentsPath = Join-Path $ScriptDir "Agents"
    if (-not (Test-Path $agentsPath)) {
        Write-Host "ERROR: CIDRA Agents not found: $agentsPath" -ForegroundColor $Red
        return $false
    }

    Write-Host "  [OK] Prerequisites check passed" -ForegroundColor $Green
    return $true
}

function Install-CIDRA {
    param([string]$TargetPath)

    Write-Host ""
    Write-Host "Installing CIDRA to: $TargetPath" -ForegroundColor $Yellow

    # Create .cidra directory
    $cidraDir = Join-Path $TargetPath ".cidra"

    if ((Test-Path $cidraDir) -and -not $Force) {
        Write-Host "ERROR: CIDRA already installed. Use -Force to overwrite." -ForegroundColor $Red
        return $false
    }

    # Create directories
    $directories = @(
        $cidraDir,
        (Join-Path $cidraDir "Agents"),
        (Join-Path $cidraDir "shared"),
        (Join-Path $cidraDir "output")
    )

    foreach ($dir in $directories) {
        if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
            Write-Host "  Created: $dir" -ForegroundColor $Green
        }
    }

    # Copy agents
    Write-Host "  Copying agents..." -ForegroundColor $Yellow
    $agentsSource = Join-Path $ScriptDir "Agents"
    $agentsTarget = Join-Path $cidraDir "Agents"
    Copy-Item -Path "$agentsSource\*" -Destination $agentsTarget -Recurse -Force

    # Copy manifest if exists
    $manifestSource = Join-Path $ScriptDir "cidra.manifest.yaml"
    if (Test-Path $manifestSource) {
        Write-Host "  Copying manifest..." -ForegroundColor $Yellow
        Copy-Item -Path $manifestSource -Destination $cidraDir -Force
    }

    # Create project config
    Write-Host "  Creating project configuration..." -ForegroundColor $Yellow
    $configContent = @"
# CIDRA Project Configuration
# Generated by CIDRA installer on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

project:
  name: "$(Split-Path $TargetPath -Leaf)"
  version: "1.0.0"

cidra:
  version: "1.0.0"
  installed: "$(Get-Date -Format "yyyy-MM-dd")"

chunker:
  default_strategy: "auto"
  output_directory: "./CHUNKS/"

documenter:
  template: "enterprise_7_file"
  language: "english"
  output_directory: "./Screens/"

recommender:
  default_risk_tolerance: "medium"
  include_cost_analysis: true
"@
    $configPath = Join-Path $cidraDir "config.yaml"
    Set-Content -Path $configPath -Value $configContent

    # Install IDE integrations
    Install-Integrations -TargetPath $TargetPath

    Write-Host ""
    Write-Host "CIDRA installed successfully!" -ForegroundColor $Green
    return $true
}

function Install-Integrations {
    param([string]$TargetPath)

    Write-Host "  Installing IDE integrations..." -ForegroundColor $Yellow

    $protocolsPath = Join-Path $ScriptDir "Protocols"

    # Cursor integration (.cursorrules)
    $cursorRulesSource = Join-Path $protocolsPath ".cursor\.cursorrules"
    if (Test-Path $cursorRulesSource) {
        $cursorRulesTarget = Join-Path $TargetPath ".cursorrules"
        if (Test-Path $cursorRulesTarget) {
            # Merge with existing
            $existingContent = Get-Content $cursorRulesTarget -Raw -Encoding UTF8
            if (-not $existingContent.Contains("CIDRA")) {
                $cidraContent = Get-Content $cursorRulesSource -Raw -Encoding UTF8
                $mergedContent = $existingContent + "`n`n# CIDRA Integration`n" + $cidraContent
                Set-Content -Path $cursorRulesTarget -Value $mergedContent -Encoding UTF8
                Write-Host "    [MERGED] .cursorrules" -ForegroundColor $Green
            } else {
                Write-Host "    [SKIP] .cursorrules (CIDRA already present)" -ForegroundColor $Yellow
            }
        } else {
            Copy-Item -Path $cursorRulesSource -Destination $cursorRulesTarget
            Write-Host "    [CREATED] .cursorrules" -ForegroundColor $Green
        }
    }

    # VS Code integration
    $vscodeSource = Join-Path $protocolsPath ".vscode\cidra-settings.json"
    if (Test-Path -LiteralPath $vscodeSource) {
        $vscodeDir = Join-Path $TargetPath ".vscode"
        if (-not (Test-Path -LiteralPath $vscodeDir)) {
            New-Item -ItemType Directory -Path $vscodeDir -Force | Out-Null
        }
        $vscodeTarget = Join-Path $vscodeDir "cidra-settings.json"
        if ((Test-Path -LiteralPath $vscodeTarget) -and -not $Force) {
            Write-Host "    [SKIP] .vscode/cidra-settings.json (exists; use -Force to overwrite)" -ForegroundColor $Yellow
        } else {
            Copy-Item -Path $vscodeSource -Destination $vscodeTarget -Force
            Write-Host "    [CREATED] .vscode/cidra-settings.json" -ForegroundColor $Green
            Write-Host "    Note: Merge with settings.json manually if needed" -ForegroundColor $Yellow
        }
    }

    # Claude Code integration
    $claudeSource = Join-Path $protocolsPath ".claude\CLAUDE.md"
    if (Test-Path $claudeSource) {
        $claudeTarget = Join-Path $TargetPath "CLAUDE.md"
        if (Test-Path $claudeTarget) {
            $existingContent = Get-Content $claudeTarget -Raw -Encoding UTF8
            if (-not $existingContent.Contains("CIDRA")) {
                $cidraContent = Get-Content $claudeSource -Raw -Encoding UTF8
                $appendContent = "`n`n# CIDRA Framework Integration`n`n" + $cidraContent
                [System.IO.File]::AppendAllText($claudeTarget, $appendContent, (New-Object System.Text.UTF8Encoding($false)))
                Write-Host "    [APPENDED] CLAUDE.md" -ForegroundColor $Green
            } else {
                Write-Host "    [SKIP] CLAUDE.md (CIDRA already present)" -ForegroundColor $Yellow
            }
        } else {
            Copy-Item -Path $claudeSource -Destination $claudeTarget
            Write-Host "    [CREATED] CLAUDE.md" -ForegroundColor $Green
        }
    }

    # Claude Code slash command templates (project-agnostic)
    $commandsSource = Join-Path $protocolsPath ".claude\commands"
    if (Test-Path -LiteralPath $commandsSource) {
        $claudeDir = Join-Path $TargetPath ".claude"
        if (-not (Test-Path -LiteralPath $claudeDir)) {
            New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null
        }
        $commandsTarget = Join-Path $claudeDir "commands"
        if (Test-Path -LiteralPath $commandsTarget) {
            if ($Force) {
                # Full replace: remove stale files first so renamed/removed
                # commands from older framework versions do not linger.
                Remove-Item -LiteralPath $commandsTarget -Recurse -Force
                Copy-Item -Path $commandsSource -Destination $claudeDir -Recurse -Force
                $cmdCount = (Get-ChildItem -LiteralPath $commandsTarget -Recurse -File -ErrorAction SilentlyContinue).Count
                Write-Host "    [REPLACED] .claude\commands\ ($cmdCount template(s) forced)" -ForegroundColor $Green
            } else {
                # Merge: copy only files not already present.
                $copied = 0
                Get-ChildItem -LiteralPath $commandsSource -Recurse -File | ForEach-Object {
                    $rel = $_.FullName.Substring($commandsSource.Length).TrimStart('\','/')
                    $dest = Join-Path $commandsTarget $rel
                    $destDir = Split-Path $dest -Parent
                    if (-not (Test-Path -LiteralPath $destDir)) {
                        New-Item -ItemType Directory -Path $destDir -Force | Out-Null
                    }
                    if (-not (Test-Path -LiteralPath $dest)) {
                        Copy-Item -LiteralPath $_.FullName -Destination $dest -Force
                        $copied++
                    }
                }
                if ($copied -gt 0) {
                    Write-Host "    [MERGED] .claude\commands\ ($copied new file(s) added)" -ForegroundColor $Green
                } else {
                    Write-Host "    [SKIP] .claude\commands\ (already present; use -Force to fully replace)" -ForegroundColor $Yellow
                }
            }
        } else {
            Copy-Item -Path $commandsSource -Destination $claudeDir -Recurse -Force
            $cmdCount = (Get-ChildItem -LiteralPath $commandsTarget -Recurse -File -ErrorAction SilentlyContinue).Count
            Write-Host "    [CREATED] .claude\commands\ ($cmdCount template(s))" -ForegroundColor $Green
        }
    } else {
        Write-Host "    [WARN] .claude\commands not found in framework; slash commands will not be available" -ForegroundColor $Yellow
    }
}

function Uninstall-CIDRA {
    param([string]$TargetPath)

    Write-Host ""
    Write-Host "Uninstalling CIDRA from: $TargetPath" -ForegroundColor $Yellow

    $cidraDir = Join-Path $TargetPath ".cidra"

    if (-not (Test-Path $cidraDir)) {
        Write-Host "CIDRA is not installed in this project." -ForegroundColor $Yellow
        return $true
    }

    # Remove .cidra directory
    Remove-Item -Path $cidraDir -Recurse -Force
    Write-Host "  Removed: .cidra/" -ForegroundColor $Green

    # Note about manual cleanup
    Write-Host ""
    Write-Host "Note: The following files may contain CIDRA references:" -ForegroundColor $Yellow
    Write-Host "  - .cursorrules (CIDRA section)"
    Write-Host "  - .vscode/cidra-settings.json"
    Write-Host "  - .claude/commands/ (brainstorm.md, chunk.md, document.md, recommend.md + subfolders)"
    Write-Host "  - CLAUDE.md (CIDRA section)"
    Write-Host "Please remove these manually if desired." -ForegroundColor $Yellow

    Write-Host ""
    Write-Host "CIDRA uninstalled successfully!" -ForegroundColor $Green
    return $true
}

function Show-PostInstall {
    Write-Host ""
    Write-Host ("=" * 50) -ForegroundColor $Cyan
    Write-Host "  CIDRA Installation Complete!" -ForegroundColor $Green
    Write-Host ("=" * 50) -ForegroundColor $Cyan
    Write-Host ""
    Write-Host "Available Commands:" -ForegroundColor $Yellow
    Write-Host ""
    Write-Host "  THE_BRAINSTORMER_AGENT (Stage 0):" -ForegroundColor $Cyan
    Write-Host "    /brainstorm             - Goal elicitation, gap analysis, blueprint"
    Write-Host "    /brainstorm:format      - Show recommended documentation format"
    Write-Host "    /brainstorm:gap         - Re-issue MISSING_INPUTS.md checklist"
    Write-Host "    /brainstorm:status      - Show current brainstormer understanding"
    Write-Host ""
    Write-Host "  THE_CHUNKER_AGENT (Stage 1):" -ForegroundColor $Cyan
    Write-Host "    /chunk [path]           - Chunk code at path"
    Write-Host "    /chunk:analyze [path]   - Preview chunking plan"
    Write-Host "    /chunk:status           - Show chunking progress"
    Write-Host ""
    Write-Host "  THE_DOCUMENTER_AGENT (Stage 2):" -ForegroundColor $Cyan
    Write-Host "    /document:setup         - One-time project config"
    Write-Host "    /document [component]   - Document a component"
    Write-Host "    /document:validate      - Run 100-point validation"
    Write-Host "    /document:fix           - Auto-fix issues"
    Write-Host ""
    Write-Host "  THE_RECOMMENDER_AGENT (Stage 3):" -ForegroundColor $Cyan
    Write-Host "    /recommend [component]  - Get recommendations"
    Write-Host "    /recommend:compare      - Compare technologies"
    Write-Host "    /recommend:risk         - Risk assessment"
    Write-Host ""
    Write-Host "Getting Started:" -ForegroundColor $Yellow
    Write-Host "  1. Open a Claude Code chat in this project"
    Write-Host "  2. Type /brainstorm  (answers the 3 pivotal questions, produces blueprint)"
    Write-Host "  3. Type /chunk:analyze Source Code, then /chunk Source Code"
    Write-Host "  4. Type /document:setup, then /document <COMPONENT>"
    Write-Host "  5. /document:validate ... /document:fix until 100/100"
    Write-Host "  6. Optional: /recommend <COMPONENT>"
    Write-Host ""
}

# Main execution
if ($Help) {
    Show-Help
    exit 0
}

Show-Banner

# Check path BEFORE Resolve-Path so the friendly error in Test-Prerequisites fires
# instead of Resolve-Path's raw "Cannot find path" error.
if (-not (Test-Path -LiteralPath $ProjectPath)) {
    Write-Host "ERROR: Project path does not exist: $ProjectPath" -ForegroundColor $Red
    exit 1
}
$TargetPath = Resolve-Path -LiteralPath $ProjectPath

if (-not (Test-Prerequisites)) {
    exit 1
}

if ($Uninstall) {
    $result = Uninstall-CIDRA -TargetPath $TargetPath
} else {
    $result = Install-CIDRA -TargetPath $TargetPath
    if ($result) {
        Show-PostInstall
    }
}

if ($result) {
    exit 0
} else {
    exit 1
}
