#!/bin/bash
# CIDRA Framework - Unix/Mac Installer
# Usage: ./install.sh [-p <path>] [-f] [-u] [-h]
#
# Examples:
#   ./install.sh                    # Install to current directory
#   ./install.sh -p /path/to/project  # Install to specific project
#   ./install.sh -f                 # Force overwrite
#   ./install.sh -u                 # Uninstall

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Defaults
PROJECT_PATH="."
FORCE=false
UNINSTALL=false

# Script directory (CIDRA framework root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

show_banner() {
    echo ""
    echo -e "${CYAN}  ██████╗██╗██████╗ ██████╗  █████╗ ${NC}"
    echo -e "${CYAN} ██╔════╝██║██╔══██╗██╔══██╗██╔══██╗${NC}"
    echo -e "${CYAN} ██║     ██║██║  ██║██████╔╝███████║${NC}"
    echo -e "${CYAN} ██║     ██║██║  ██║██╔══██╗██╔══██║${NC}"
    echo -e "${CYAN} ╚██████╗██║██████╔╝██║  ██║██║  ██║${NC}"
    echo -e "${CYAN}  ╚═════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝${NC}"
    echo ""
    echo -e "${YELLOW} CIDRA Framework Installer${NC}"
    echo -e "${YELLOW} Chunker + Interpreter + Documenter + Recommender + Applicator${NC}"
    echo -e "${YELLOW} Version 1.0.0${NC}"
    echo ""
}

show_help() {
    show_banner
    echo -e "${GREEN}Usage: ./install.sh [options]${NC}"
    echo ""
    echo "Options:"
    echo "  -p <path>    Target project directory (default: current)"
    echo "  -f           Force overwrite existing installation"
    echo "  -u           Uninstall CIDRA from project"
    echo "  -h           Show this help message"
    echo ""
    echo "Examples:"
    echo "  ./install.sh"
    echo "  ./install.sh -p /path/to/project"
    echo "  ./install.sh -f"
    echo "  ./install.sh -u"
    echo ""
    echo "One-liner install from GitHub:"
    echo "  curl -sSL https://raw.githubusercontent.com/iliyaruvinsky/enterprise_cidra_framework/main/Scripts/install.sh | bash"
    echo ""
}

check_prerequisites() {
    echo -e "${YELLOW}Checking prerequisites...${NC}"

    # Check if project path exists
    if [ ! -d "$PROJECT_PATH" ]; then
        echo -e "${RED}ERROR: Project path does not exist: $PROJECT_PATH${NC}"
        return 1
    fi

    # Check if CIDRA framework files exist
    if [ ! -d "$SCRIPT_DIR/Agents" ]; then
        echo -e "${RED}ERROR: CIDRA Agents not found: $SCRIPT_DIR/Agents${NC}"
        return 1
    fi

    echo -e "  ${GREEN}[OK] Prerequisites check passed${NC}"
    return 0
}

install_cidra() {
    local target_path="$1"

    echo ""
    echo -e "${YELLOW}Installing CIDRA to: $target_path${NC}"

    local cidra_dir="$target_path/.cidra"

    # Check existing installation
    if [ -d "$cidra_dir" ] && [ "$FORCE" = false ]; then
        echo -e "${RED}ERROR: CIDRA already installed. Use -f to overwrite.${NC}"
        return 1
    fi

    # Create directories
    mkdir -p "$cidra_dir/Agents"
    mkdir -p "$cidra_dir/shared"
    mkdir -p "$cidra_dir/output"
    echo -e "  ${GREEN}Created: .cidra/${NC}"

    # Copy agents
    echo -e "  ${YELLOW}Copying agents...${NC}"
    cp -r "$SCRIPT_DIR/Agents/"* "$cidra_dir/Agents/" 2>/dev/null || true

    # Copy manifest if exists
    if [ -f "$SCRIPT_DIR/cidra.manifest.yaml" ]; then
        echo -e "  ${YELLOW}Copying manifest...${NC}"
        cp "$SCRIPT_DIR/cidra.manifest.yaml" "$cidra_dir/"
    fi

    # Create project config
    echo -e "  ${YELLOW}Creating project configuration...${NC}"
    local project_name=$(basename "$target_path")
    cat > "$cidra_dir/config.yaml" << EOF
# CIDRA Project Configuration
# Generated by CIDRA installer on $(date "+%Y-%m-%d %H:%M:%S")

project:
  name: "$project_name"
  version: "1.0.0"

cidra:
  version: "1.0.0"
  installed: "$(date "+%Y-%m-%d")"

chunker:
  default_strategy: "auto"
  output_directory: "./CHUNKS/"

documenter:
  template: "enterprise_7_file"
  language: "english"
  output_directory: "./Screens/"

recommender:
  default_risk_tolerance: "medium"
  include_cost_analysis: true
EOF

    # Install integrations
    install_integrations "$target_path"

    echo ""
    echo -e "${GREEN}CIDRA installed successfully!${NC}"
    return 0
}

install_integrations() {
    local target_path="$1"
    local protocols_path="$SCRIPT_DIR/Protocols"

    echo -e "  ${YELLOW}Installing IDE integrations...${NC}"

    # Cursor integration (.cursorrules)
    local cursor_source="$protocols_path/.cursor/.cursorrules"
    if [ -f "$cursor_source" ]; then
        local cursor_target="$target_path/.cursorrules"
        if [ -f "$cursor_target" ]; then
            if ! grep -q "CIDRA" "$cursor_target"; then
                echo -e "\n\n# CIDRA Integration\n" >> "$cursor_target"
                cat "$cursor_source" >> "$cursor_target"
                echo -e "    ${GREEN}[MERGED] .cursorrules${NC}"
            else
                echo -e "    ${YELLOW}[SKIP] .cursorrules (CIDRA already present)${NC}"
            fi
        else
            cp "$cursor_source" "$cursor_target"
            echo -e "    ${GREEN}[CREATED] .cursorrules${NC}"
        fi
    fi

    # VS Code integration
    local vscode_source="$protocols_path/.vscode/cidra-settings.json"
    if [ -f "$vscode_source" ]; then
        mkdir -p "$target_path/.vscode"
        cp "$vscode_source" "$target_path/.vscode/cidra-settings.json"
        echo -e "    ${GREEN}[CREATED] .vscode/cidra-settings.json${NC}"
        echo -e "    ${YELLOW}Note: Merge with settings.json manually if needed${NC}"
    fi

    # Claude Code integration
    local claude_source="$protocols_path/.claude/CLAUDE.md"
    if [ -f "$claude_source" ]; then
        local claude_target="$target_path/CLAUDE.md"
        if [ -f "$claude_target" ]; then
            if ! grep -q "CIDRA" "$claude_target"; then
                echo -e "\n\n# CIDRA Framework Integration\n\n" >> "$claude_target"
                cat "$claude_source" >> "$claude_target"
                echo -e "    ${GREEN}[APPENDED] CLAUDE.md${NC}"
            else
                echo -e "    ${YELLOW}[SKIP] CLAUDE.md (CIDRA already present)${NC}"
            fi
        else
            cp "$claude_source" "$claude_target"
            echo -e "    ${GREEN}[CREATED] CLAUDE.md${NC}"
        fi
    fi
}

uninstall_cidra() {
    local target_path="$1"

    echo ""
    echo -e "${YELLOW}Uninstalling CIDRA from: $target_path${NC}"

    local cidra_dir="$target_path/.cidra"

    if [ ! -d "$cidra_dir" ]; then
        echo -e "${YELLOW}CIDRA is not installed in this project.${NC}"
        return 0
    fi

    # Remove .cidra directory
    rm -rf "$cidra_dir"
    echo -e "  ${GREEN}Removed: .cidra/${NC}"

    # Note about manual cleanup
    echo ""
    echo -e "${YELLOW}Note: The following files may contain CIDRA references:${NC}"
    echo "  - .cursorrules (CIDRA section)"
    echo "  - .vscode/cidra-settings.json"
    echo "  - CLAUDE.md (CIDRA section)"
    echo -e "${YELLOW}Please remove these manually if desired.${NC}"

    echo ""
    echo -e "${GREEN}CIDRA uninstalled successfully!${NC}"
    return 0
}

show_post_install() {
    echo ""
    echo -e "${CYAN}==================================================${NC}"
    echo -e "${GREEN}  CIDRA Installation Complete!${NC}"
    echo -e "${CYAN}==================================================${NC}"
    echo ""
    echo -e "${YELLOW}Available Commands:${NC}"
    echo ""
    echo -e "${CYAN}  THE_CHUNKER_AGENT:${NC}"
    echo "    /chunk [path]           - Chunk code at path"
    echo "    /chunk:analyze [path]   - Preview chunking plan"
    echo "    /chunk:status           - Show chunking progress"
    echo ""
    echo -e "${CYAN}  THE_DOCUMENTER_AGENT:${NC}"
    echo "    /document:setup         - One-time project config"
    echo "    /document [component]   - Document a component"
    echo "    /document:validate      - Run 100-point validation"
    echo "    /document:fix           - Auto-fix issues"
    echo ""
    echo -e "${CYAN}  THE_RECOMMENDER_AGENT:${NC}"
    echo "    /recommend [component]  - Get recommendations"
    echo "    /recommend:compare      - Compare technologies"
    echo "    /recommend:risk         - Risk assessment"
    echo ""
    echo -e "${YELLOW}Getting Started:${NC}"
    echo "  1. Run /document:setup to configure your project"
    echo "  2. Run /chunk [path] to prepare your code"
    echo "  3. Run /document [component] to document"
    echo "  4. Run /recommend [component] for modernization advice"
    echo ""
}

# Parse arguments
while getopts "p:fuh" opt; do
    case $opt in
        p)
            PROJECT_PATH="$OPTARG"
            ;;
        f)
            FORCE=true
            ;;
        u)
            UNINSTALL=true
            ;;
        h)
            show_help
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            show_help
            exit 1
            ;;
    esac
done

# Main execution
show_banner

# Resolve project path
PROJECT_PATH="$(cd "$PROJECT_PATH" && pwd)"

if ! check_prerequisites; then
    exit 1
fi

if [ "$UNINSTALL" = true ]; then
    uninstall_cidra "$PROJECT_PATH"
else
    if install_cidra "$PROJECT_PATH"; then
        show_post_install
    else
        exit 1
    fi
fi
